upstream php-handler {
    server nextcloud:9000;
}

server {
    listen 80;
    root /var/www/html;
    client_max_body_size 512M;

    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Robots-Tag "noindex, nofollow" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location = /.well-known/carddav { return 301 /remote.php/dav/; }
    location = /.well-known/caldav  { return 301 /remote.php/dav/; }

    location /login/v2/poll {
    	fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
    	fastcgi_param SCRIPT_FILENAME $document_root/index.php;
    	fastcgi_param PATH_INFO /login/v2/poll;
    	fastcgi_param REQUEST_URI $request_uri;
    	fastcgi_param HTTPS off;
    	fastcgi_param modHeadersAvailable true;
    	fastcgi_param front_controller_active true;
    	include fastcgi_params;
    	fastcgi_pass php-handler;
    	fastcgi_intercept_errors on;
    	fastcgi_request_buffering off;
    }

    location ~ \.php(?:$|\/) {
        fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
        set $path_info $fastcgi_path_info;
        try_files $fastcgi_script_name =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS off;
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass php-handler;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    location ~ \.(?:css|js|woff2?|svg|gif|png|jpg|ico|map)$ {
        try_files $uri /index.php$request_uri;
        expires 6M;
        access_log off;
    }

    location / {
        rewrite ^ /index.php last;
    }
}

